apiVersion: apps/v1
kind: Deployment
metadata:
  name: nks-test-depolyment
  namespace: nks-test
spec:
  selector:
    matchLabels:
      app: nks-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nks-test
    spec:
      containers:
      - image: lalll5555/nks-test:latest
        imagePullPolicy: Always
        name: nks-test
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nks-test-service
  namespace: nks-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nks-test
  type: LoadBalancer
